### ISSUE TITLE
Couple of links in Artifacts Plugin Documentation seems broken

### ISSUE THREAD

**Issue by ashwanthkumar** [gocd/plugin-api.go.cd#64]
Thanks for the new artifacts endpoint. I'm super excited to try it out. While reading through the API documentation, I found a couple of links doesn't have a relevant section for them on the page.

- https://plugin-api.gocd.org/18.7.0/artifacts/#send-console-log
- https://plugin-api.gocd.org/18.7.0/artifacts/#get-plugin-capabilities

**Comment by ketan** [comment]
Where did you find these links @ashwanthkumar ?

**Comment by ashwanthkumar** [comment]
On https://plugin-api.gocd.org/18.7.0/artifacts/#requests-from-the-gocd-server and https://plugin-api.gocd.org/18.7.0/artifacts/#requests-to-the-gocd-server
